### ISSUE TITLE
Timestamp TULIP Virtual Port Feeds

### ISSUE THREAD

**Issue by NobodyYouKnow** [mjakuipers/TULIP-DevBoard#4]
Can each line in the various serial feeds be timestamped somehow - console, tracer and HP-il scope to assist in correlation between different feeds right now. It is hard to match up where a HPIL transaction happens in the tracer feed. Extra points to make this an option that can be turned on / off.

**Comment by mjakuipers** [comment]
Will look at adding the trace counter to the HP-IL/PILBox trace samples

**Comment by mjakuipers** [comment]
The sample counter (first column in the trace window) is now added to the samples in the HP-IL scope. This cannot be disabled, but I might go for the bonus later.
